/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.ControllerEmail;
import java.awt.Dimension;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import security.SHAHashing;

/**
 *
 * @author MSAcerPC
 */
public class VEmail extends javax.swing.JInternalFrame {
    
    int janela = 0;
    ControllerEmail controllerEmail;
    SHAHashing cryptography;
    
    public VEmail() {
        initComponents();
        controllerEmail = new ControllerEmail();
        validarVazio(true);
        
        cryptography = new SHAHashing();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel1 = new org.edisoncor.gui.panel.Panel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jtCE_serverSMTP = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jtCE_serverPorta = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jtCE_Email = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jpCE_Senha = new javax.swing.JPasswordField();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtaCE_assinatura = new javax.swing.JTextArea();
        jbCE_salvar = new javax.swing.JButton();
        jbCE_cancelar = new javax.swing.JButton();
        v1 = new javax.swing.JLabel();
        v2 = new javax.swing.JLabel();
        v3 = new javax.swing.JLabel();
        v4 = new javax.swing.JLabel();
        v5 = new javax.swing.JLabel();
        jBEdit = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setResizable(true);
        setTitle("Configuração de Email");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameClosing(evt);
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
        });

        panel1.setColorPrimario(new java.awt.Color(0, 0, 255));
        panel1.setColorSecundario(new java.awt.Color(255, 0, 0));

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Servidor SMTP");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Configuração do servidor de email (Gmail)");

        jtCE_serverSMTP.setEditable(false);

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Porta");

        jtCE_serverPorta.setEditable(false);
        jtCE_serverPorta.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtCE_serverPortaKeyTyped(evt);
            }
        });

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Email");

        jtCE_Email.setEditable(false);

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Senha");

        jpCE_Senha.setEditable(false);

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Assinatura");

        jtaCE_assinatura.setEditable(false);
        jtaCE_assinatura.setColumns(20);
        jtaCE_assinatura.setRows(5);
        jScrollPane1.setViewportView(jtaCE_assinatura);

        jbCE_salvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/OK.png"))); // NOI18N
        jbCE_salvar.setToolTipText("Guardar Servidor Email");
        jbCE_salvar.setEnabled(false);
        jbCE_salvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCE_salvarActionPerformed(evt);
            }
        });

        jbCE_cancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/Cancel.png"))); // NOI18N
        jbCE_cancelar.setToolTipText("Cancelar");
        jbCE_cancelar.setEnabled(false);
        jbCE_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCE_cancelarActionPerformed(evt);
            }
        });

        v1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        v1.setForeground(new java.awt.Color(255, 0, 0));
        v1.setText("*");

        v2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        v2.setForeground(new java.awt.Color(255, 0, 0));
        v2.setText("*");

        v3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        v3.setForeground(new java.awt.Color(255, 0, 0));
        v3.setText("*");

        v4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        v4.setForeground(new java.awt.Color(255, 0, 0));
        v4.setText("*");

        v5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        v5.setForeground(new java.awt.Color(255, 0, 0));
        v5.setText("*");

        jBEdit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/Update.png"))); // NOI18N
        jBEdit.setToolTipText("Editar Servidor Email");
        jBEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBEditActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
        panel1.setLayout(panel1Layout);
        panel1Layout.setHorizontalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(10, 10, 10)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addComponent(jtCE_serverSMTP, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(v2, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addComponent(jtCE_Email, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(v3, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addComponent(jpCE_Senha, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(v4, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(v5, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addComponent(jtCE_serverPorta, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(v1))
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(jbCE_salvar)
                        .addGap(18, 18, 18)
                        .addComponent(jbCE_cancelar)
                        .addGap(18, 18, 18)
                        .addComponent(jBEdit)))
                .addGap(70, 70, 70))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(119, 119, 119))
        );
        panel1Layout.setVerticalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jtCE_serverPorta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(v1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jtCE_serverSMTP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(v2))
                .addGap(10, 10, 10)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jtCE_Email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(v3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jpCE_Senha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(v4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(v5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbCE_salvar)
                    .addComponent(jbCE_cancelar)
                    .addComponent(jBEdit))
                .addGap(32, 32, 32))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(panel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(panel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formInternalFrameClosing(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameClosing
        janela = 0;
        validarVazio(true);
    }//GEN-LAST:event_formInternalFrameClosing

    private void jbCE_salvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCE_salvarActionPerformed
        if (jtCE_serverPorta.getText().equals("")) {
            if (validarCampos(false)) {
                cryptography.EncryptDescrypte(jpCE_Senha.getText());
                controllerEmail.manutencaoEmail("inserir", jtCE_serverSMTP.getText(), jtCE_serverPorta.getText(), jtCE_Email.getText(), jpCE_Senha.getText(), jtaCE_assinatura.getText());
//                ativarDesativarClienteCampos(false);
                validarVazio(true);
                validaBotoes(true);
                ativacampos(false);
            }
            
        } else {
            if (validarCampos(false)) {
                cryptography.EncryptDescrypte(jpCE_Senha.getText());
                controllerEmail.manutencaoEmail("alterar", jtCE_serverSMTP.getText(), jtCE_serverPorta.getText(), jtCE_Email.getText(), jpCE_Senha.getText(), jtaCE_assinatura.getText());
////                limparClienteCampos();
////                ativarDesativaBotoes(true);
////                destivarAtivarBotoes2(true);
                validarVazio(true);
                validaBotoes(true);
                ativacampos(false);
            }
        }
    }//GEN-LAST:event_jbCE_salvarActionPerformed

    private void jtCE_serverPortaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtCE_serverPortaKeyTyped
        char c = evt.getKeyChar();
        if (c < '0' || c > '9') {
            evt.consume();
        }
    }//GEN-LAST:event_jtCE_serverPortaKeyTyped

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
        try {
            controllerEmail.manutencaoPesquisa();
        } catch (IOException ex) {
            Logger.getLogger(VEmail.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_formInternalFrameOpened

    private void jBEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBEditActionPerformed
        validaBotoes(false);
        ativacampos(true);
    }//GEN-LAST:event_jBEditActionPerformed

    private void jbCE_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCE_cancelarActionPerformed
        validaBotoes(true);
        ativacampos(false);
    }//GEN-LAST:event_jbCE_cancelarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBEdit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton jbCE_cancelar;
    private javax.swing.JButton jbCE_salvar;
    public static javax.swing.JPasswordField jpCE_Senha;
    public static javax.swing.JTextField jtCE_Email;
    public static javax.swing.JTextField jtCE_serverPorta;
    public static javax.swing.JTextField jtCE_serverSMTP;
    public static javax.swing.JTextArea jtaCE_assinatura;
    private org.edisoncor.gui.panel.Panel panel1;
    private javax.swing.JLabel v1;
    private javax.swing.JLabel v2;
    private javax.swing.JLabel v3;
    private javax.swing.JLabel v4;
    private javax.swing.JLabel v5;
    // End of variables declaration//GEN-END:variables

    public void setPosicao() {
        Dimension d = this.getDesktopPane().getSize();
        this.setLocation((d.width - this.getSize().width) / 2, (d.height - this.getSize().height) / 2);
    }

    private boolean validarVazio(boolean v) {
        
        v1.setVisible(!v);
        v2.setVisible(!v);
        v3.setVisible(!v);
        v4.setVisible(!v);
        v5.setVisible(!v);
        
        return true;
    }

    private boolean validarCampos(boolean v) {
        
        if (jtCE_serverPorta.getText().equals("")) {
            v1.setVisible(!v);
            jtCE_serverPorta.requestFocus();
            return false;
        }
        if (jtCE_serverSMTP.getText().equals("")) {
            v2.setVisible(!v);
            jtCE_serverSMTP.requestFocus();
            return false;
        }
        if (jtCE_Email.getText().equals("")) {
            v3.setVisible(!v);
            jtCE_Email.requestFocus();
            return false;
        }
        if (jpCE_Senha.getText().equals("")) {
            v4.setVisible(!v);
            jpCE_Senha.requestFocus();
            return false;
        }
        if (jtaCE_assinatura.getText().equals("")) {
            v5.setVisible(!v);
            jtaCE_assinatura.requestFocus();
            return false;
        }
        return true;
    }
    
    public void validaBotoes(Boolean v) {
        jBEdit.setEnabled(v);
        jbCE_cancelar.setEnabled(!v);
        jbCE_salvar.setEnabled(!v);
    }
    public void ativacampos(boolean v){
        jtaCE_assinatura.setEditable(v);
        jtCE_Email.setEditable(v);
        jtCE_serverSMTP.setEditable(v);
        jtCE_serverPorta.setEditable(v);
        jpCE_Senha.setEditable(v);
    }
}
