/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.ControllerCliente;
import controller.ControllerEmail;
import email.EnviarEmail;
import java.awt.Dimension;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;
import model.Item;
import static view.VPagamentos.jcbClientePagamento;

/**
 *
 * @author Carlos
 */
public class VEnviandoEmail extends javax.swing.JInternalFrame {

    int janela = 0;
    EnviarEmail envioEmail;
    ControllerCliente controllerCliente;
    ControllerEmail controllerEmail;
    public static String caminho;
    public static String usuario;
    public VEnviandoEmail() {
        initComponents();
        
        envioEmail = new EnviarEmail();
        controllerCliente = new ControllerCliente();
        //carregaImgagem();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLFromEmail = new javax.swing.JLabel();
        tfPara = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        tfAssunto = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        taMensagem = new javax.swing.JTextArea();
        jBEnviaEmail = new javax.swing.JButton();
        jlMensagem = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jBAnexoFile = new javax.swing.JButton();
        jBAnexoImagem = new javax.swing.JButton();
        jComboBoxEmail = new javax.swing.JComboBox();
        jTEmail = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setResizable(true);
        setTitle("Enviando Email");
        setPreferredSize(new java.awt.Dimension(700, 493));
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameClosing(evt);
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Formulário abaixo para envio de email ");

        jLFromEmail.setText("Para.:");

        jLabel5.setText("Assunto.:");

        taMensagem.setColumns(20);
        taMensagem.setRows(5);
        jScrollPane1.setViewportView(taMensagem);

        jBEnviaEmail.setBackground(new java.awt.Color(0, 51, 255));
        jBEnviaEmail.setForeground(new java.awt.Color(102, 102, 102));
        jBEnviaEmail.setText("Enviar");
        jBEnviaEmail.setToolTipText("Enviar Email");
        jBEnviaEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBEnviaEmailActionPerformed(evt);
            }
        });

        jlMensagem.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jlMensagem.setForeground(new java.awt.Color(255, 0, 0));

        jBAnexoFile.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/icon_attachment.gif"))); // NOI18N
        jBAnexoFile.setToolTipText("Anexar ficheiro ");
        jBAnexoFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAnexoFileActionPerformed(evt);
            }
        });

        jBAnexoImagem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/image.gif"))); // NOI18N
        jBAnexoImagem.setToolTipText("Anexar imagens");
        jBAnexoImagem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAnexoImagemActionPerformed(evt);
            }
        });

        jComboBoxEmail.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBoxEmail.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBoxEmailItemStateChanged(evt);
            }
        });
        jComboBoxEmail.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jComboBoxEmailMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jComboBoxEmailMouseExited(evt);
            }
        });

        jTEmail.setText("Email:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLFromEmail, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTEmail, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfAssunto)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jBEnviaEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jBAnexoFile, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jBAnexoImagem, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 567, Short.MAX_VALUE)
                            .addComponent(tfPara, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jComboBoxEmail, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(10, 10, 10))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(jlMensagem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(288, 288, 288))
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxEmail)
                    .addComponent(jTEmail))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfPara)
                    .addComponent(jLFromEmail))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfAssunto)
                    .addComponent(jLabel5))
                .addGap(26, 26, 26)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 182, Short.MAX_VALUE)
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jBAnexoFile)
                    .addComponent(jBAnexoImagem)
                    .addComponent(jBEnviaEmail))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jlMensagem, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formInternalFrameClosing(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameClosing
        janela = 0;
        
        limparCampos();
    }//GEN-LAST:event_formInternalFrameClosing

    private void jBEnviaEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBEnviaEmailActionPerformed
       String from = "mcsolutioncv@gmail.com";
       if(!tfPara.isVisible()){
           try {
              envioEmail.EnviaEmail(from, tfAssunto.getText(), taMensagem.getText(), caminho);
          } catch (IOException ex) {
              jlMensagem.setText("Erro no emial "+ex.getMessage());
          }
       }
       else if(tfPara.getText().equals("")){
          jlMensagem.setText("O destinário é obrigátorio para o envio de email, por favor preencha este campo!");
          tfPara.setFocusable(true);
      }else{        
          try {
              envioEmail.EnviaEmail(tfPara.getText(), tfAssunto.getText(), taMensagem.getText(), caminho);
          } catch (IOException ex) {
              jlMensagem.setText("Erro no emial "+ex.getMessage());
          }
      }
    }//GEN-LAST:event_jBEnviaEmailActionPerformed

    private void jBAnexoFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAnexoFileActionPerformed
        carregaFicherio();
    }//GEN-LAST:event_jBAnexoFileActionPerformed

    private void jBAnexoImagemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAnexoImagemActionPerformed
        carregaImgagem();
    }//GEN-LAST:event_jBAnexoImagemActionPerformed

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
        try {
            controllerCliente.addEmailToComo(jComboBoxEmail);
            controllerEmail = new ControllerEmail();
            controllerEmail.manutencaoDadosToEmail();
        } catch (IOException ex) {
            Logger.getLogger(VEnviandoEmail.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_formInternalFrameOpened

    private void jComboBoxEmailMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBoxEmailMouseExited
       
    }//GEN-LAST:event_jComboBoxEmailMouseExited

    private void jComboBoxEmailMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBoxEmailMouseClicked
        if(jComboBoxEmail.getSelectedIndex()!=0){
           tfPara.setText(jComboBoxEmail.getSelectedItem().toString());
       }
    }//GEN-LAST:event_jComboBoxEmailMouseClicked

    private void jComboBoxEmailItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBoxEmailItemStateChanged
       if (evt.getStateChange() == java.awt.event.ItemEvent.SELECTED) {
                try{
               // Item selected_item = (Item) jComboBoxEmail.getSelectedItem();                
                //int valor = controllerPagamento.getValorPagamento(selected_item.getIdMatricula(),selected_item.getId());
                tfPara.setText((String) jComboBoxEmail.getSelectedItem());
                }catch(java.lang.ClassCastException ex){
                    System.out.println("ok");
                }
            } 
    }//GEN-LAST:event_jComboBoxEmailItemStateChanged

public String carregaImgagem() {
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setDialogTitle("Carregar imagem");

        fileChooser.setFileSelectionMode(JFileChooser.FILES_ONLY);
        FileNameExtensionFilter filter = new FileNameExtensionFilter(
                "PNG, JPG, GIF, and BMP Images", "PNG", "jpg", "gif", "bmp");
        fileChooser.setFileFilter(filter);
        
        // int a = fileChooser.showOpenDialog(null);
        if (fileChooser.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
            File arquivo = fileChooser.getSelectedFile();//arquivo   
            
            caminho = arquivo.getAbsolutePath();
          //  JOptionPane.showMessageDialog(this, caminho);
        }
        
        return caminho;
    }
public String carregaFicherio() {
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setDialogTitle("Carregar ficheiro");

        fileChooser.setFileSelectionMode(JFileChooser.FILES_ONLY);
                
        // int a = fileChooser.showOpenDialog(null);
        if (fileChooser.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
            File arquivo = fileChooser.getSelectedFile();//arquivo   
            
            caminho = arquivo.getAbsolutePath();
            //JOptionPane.showMessageDialog(this, caminho);
        }
        
        return caminho;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBAnexoFile;
    private javax.swing.JButton jBAnexoImagem;
    private javax.swing.JButton jBEnviaEmail;
    public static javax.swing.JComboBox jComboBoxEmail;
    public static javax.swing.JLabel jLFromEmail;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    public static javax.swing.JLabel jTEmail;
    private javax.swing.JLabel jlMensagem;
    private javax.swing.JTextArea taMensagem;
    private javax.swing.JTextField tfAssunto;
    public static javax.swing.JTextField tfPara;
    // End of variables declaration//GEN-END:variables

    public void setPosicao() {
        Dimension d = this.getDesktopPane().getSize();
        this.setLocation((d.width - this.getSize().width) / 2, (d.height - this.getSize().height) / 2);
    }
    
    public void limparCampos(){
        tfPara.setText("");
        tfAssunto.setText("");
        taMensagem.setText("");
        jlMensagem.setText("");
    }
}
