/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.ControllerFuncionario;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Graphics2D;
import java.awt.geom.AffineTransform;
import java.awt.image.BufferedImage;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.IOException;
import java.io.InputStream;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.border.LineBorder;
import javax.swing.filechooser.FileNameExtensionFilter;
import persistence.Conexao;

/**
 *
 * @author Carlos
 */
public class VFuncionario extends javax.swing.JInternalFrame {

    int janela = 0;
    String seta_look;
    String localFoto;
    ControllerFuncionario controllerFuncinario;
    byte[] bytes;

    /**
     * Creates new form Teste
     */
    public VFuncionario() {
        initComponents();
        jbNovo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbNovo.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jbNovo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        jbGuardar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbGuardar.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jbGuardar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        jbCancelar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbCancelar.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jbCancelar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        jbEditar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbEditar.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jbEditar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        jbApagar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbApagar.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jbApagar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        jbImprimir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbImprimir.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jbImprimir.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        Date ds = new Date();
        jdFun_dtReg.setDate(ds);

        jtFuncionario.setAutoCreateRowSorter(true);

        controllerFuncinario = new ControllerFuncionario();
        
        getRootPane().setDefaultButton(jbFun_pesquisar);
        
        jtFun_cod.setVisible(false);
        jLabel6.setVisible(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jbNovo = new javax.swing.JButton();
        jbGuardar = new javax.swing.JButton();
        jbEditar = new javax.swing.JButton();
        jbApagar = new javax.swing.JButton();
        jbCancelar = new javax.swing.JButton();
        jbImprimir = new javax.swing.JButton();
        jTabFun = new javax.swing.JTabbedPane();
        jpFun_listar = new javax.swing.JPanel();
        jtFun_pesq = new javax.swing.JTextField();
        jbFun_pesquisar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtFuncionario = new javax.swing.JTable();
        jpFun_dados = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jcFun_sexo = new javax.swing.JComboBox();
        jcFun_status = new javax.swing.JComboBox();
        jLabel12 = new javax.swing.JLabel();
        jpFun_foto = new javax.swing.JPanel();
        jlFoto = new javax.swing.JLabel();
        jbCli_procurar = new javax.swing.JButton();
        jbCli_limpar = new javax.swing.JButton();
        jtFun_cod = new javax.swing.JTextField();
        jtFun_nome = new javax.swing.JTextField();
        jtFun_bi = new javax.swing.JTextField();
        jtFun_telm = new javax.swing.JTextField();
        jdFun_dtNasc = new com.toedter.calendar.JDateChooser();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jtFun_cp = new javax.swing.JTextField();
        jdFun_dtReg = new com.toedter.calendar.JDateChooser();
        jtFun_morada = new javax.swing.JTextField();
        jtFun_email = new javax.swing.JTextField();

        setClosable(true);
        setIconifiable(true);
        setResizable(true);
        setTitle("Manutenção de funcionário");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameClosing(evt);
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
        });

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Opções");

        jbNovo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/Add.png"))); // NOI18N
        jbNovo.setText("Novo");
        jbNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbNovoActionPerformed(evt);
            }
        });

        jbGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/salvar.png"))); // NOI18N
        jbGuardar.setText("Guardar");
        jbGuardar.setEnabled(false);
        jbGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbGuardarActionPerformed(evt);
            }
        });

        jbEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/Modify.png"))); // NOI18N
        jbEditar.setText("Editar");
        jbEditar.setEnabled(false);
        jbEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbEditarActionPerformed(evt);
            }
        });

        jbApagar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/Remove.png"))); // NOI18N
        jbApagar.setText("Apagar");
        jbApagar.setEnabled(false);
        jbApagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbApagarActionPerformed(evt);
            }
        });

        jbCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/Close.png"))); // NOI18N
        jbCancelar.setText("Cancelar");
        jbCancelar.setEnabled(false);
        jbCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCancelarActionPerformed(evt);
            }
        });

        jbImprimir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/Print.png"))); // NOI18N
        jbImprimir.setText("Imprimir");
        jbImprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbImprimirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jbCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jbEditar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jbApagar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jbNovo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jbGuardar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jbImprimir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbNovo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbGuardar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbEditar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbApagar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbCancelar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jbImprimir)
                .addGap(20, 20, 20))
        );

        jTabFun.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTabFun.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTabFunMouseClicked(evt);
            }
        });

        jtFun_pesq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtFun_pesqActionPerformed(evt);
            }
        });

        jbFun_pesquisar.setText("Pesquisar");
        jbFun_pesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbFun_pesquisarActionPerformed(evt);
            }
        });

        jtFuncionario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Cod", "Nome", "Tel", "Morada", "Permissão", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtFuncionario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtFuncionarioMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtFuncionario);
        if (jtFuncionario.getColumnModel().getColumnCount() > 0) {
            jtFuncionario.getColumnModel().getColumn(0).setMinWidth(40);
            jtFuncionario.getColumnModel().getColumn(0).setMaxWidth(40);
            jtFuncionario.getColumnModel().getColumn(2).setMinWidth(80);
            jtFuncionario.getColumnModel().getColumn(2).setMaxWidth(80);
            jtFuncionario.getColumnModel().getColumn(3).setMinWidth(80);
            jtFuncionario.getColumnModel().getColumn(3).setMaxWidth(80);
            jtFuncionario.getColumnModel().getColumn(4).setMinWidth(80);
            jtFuncionario.getColumnModel().getColumn(4).setMaxWidth(80);
            jtFuncionario.getColumnModel().getColumn(5).setMinWidth(60);
            jtFuncionario.getColumnModel().getColumn(5).setMaxWidth(60);
        }

        javax.swing.GroupLayout jpFun_listarLayout = new javax.swing.GroupLayout(jpFun_listar);
        jpFun_listar.setLayout(jpFun_listarLayout);
        jpFun_listarLayout.setHorizontalGroup(
            jpFun_listarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpFun_listarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpFun_listarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 570, Short.MAX_VALUE)
                    .addGroup(jpFun_listarLayout.createSequentialGroup()
                        .addComponent(jtFun_pesq, javax.swing.GroupLayout.PREFERRED_SIZE, 483, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbFun_pesquisar)))
                .addContainerGap())
        );
        jpFun_listarLayout.setVerticalGroup(
            jpFun_listarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpFun_listarLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jpFun_listarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtFun_pesq, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbFun_pesquisar))
                .addGap(20, 20, 20)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 335, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabFun.addTab("Lista de Funcionário", jpFun_listar);

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Identificação"));

        jLabel2.setText("Nome");

        jLabel3.setText("BI");

        jLabel4.setText("Morada");

        jLabel5.setText("Data Reg.");
        jLabel5.setToolTipText("Data Registo");

        jLabel6.setText("Codigo");

        jLabel7.setText("Email");

        jLabel8.setText("Data Nasc.");
        jLabel8.setToolTipText("Data Nacimento");

        jLabel11.setText("Telemovel");

        jcFun_sexo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Selecione...", "Masculino", "Feminino" }));
        jcFun_sexo.setEnabled(false);

        jcFun_status.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Selecione...", "Ativo", "Inativo" }));
        jcFun_status.setEnabled(false);

        jLabel12.setText("C.P.");
        jLabel12.setToolTipText("Código Postal");

        jpFun_foto.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jlFoto.setBackground(new java.awt.Color(255, 255, 255));
        jlFoto.setForeground(new java.awt.Color(102, 102, 102));
        jlFoto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlFoto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/fotoCliente.png"))); // NOI18N
        jlFoto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlFotoMouseClicked(evt);
            }
        });

        jbCli_procurar.setText("Procurar");
        jbCli_procurar.setEnabled(false);
        jbCli_procurar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCli_procurarActionPerformed(evt);
            }
        });

        jbCli_limpar.setText("Limpar");
        jbCli_limpar.setEnabled(false);
        jbCli_limpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCli_limparActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpFun_fotoLayout = new javax.swing.GroupLayout(jpFun_foto);
        jpFun_foto.setLayout(jpFun_fotoLayout);
        jpFun_fotoLayout.setHorizontalGroup(
            jpFun_fotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpFun_fotoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpFun_fotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jlFoto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jpFun_fotoLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jbCli_procurar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbCli_limpar)))
                .addContainerGap())
        );
        jpFun_fotoLayout.setVerticalGroup(
            jpFun_fotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpFun_fotoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlFoto, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpFun_fotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbCli_procurar)
                    .addComponent(jbCli_limpar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jtFun_cod.setEditable(false);
        jtFun_cod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtFun_codActionPerformed(evt);
            }
        });

        jtFun_nome.setEditable(false);

        jtFun_bi.setEditable(false);
        jtFun_bi.setMinimumSize(new java.awt.Dimension(20, 20));
        jtFun_bi.setPreferredSize(new java.awt.Dimension(20, 20));
        jtFun_bi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtFun_biActionPerformed(evt);
            }
        });

        jtFun_telm.setEditable(false);
        jtFun_telm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtFun_telmActionPerformed(evt);
            }
        });

        jdFun_dtNasc.setEnabled(false);

        jLabel13.setText("Sexo");

        jLabel14.setText("Estado");

        jtFun_cp.setEditable(false);

        jdFun_dtReg.setEnabled(false);

        jtFun_morada.setEditable(false);
        jtFun_morada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtFun_moradaActionPerformed(evt);
            }
        });

        jtFun_email.setEditable(false);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, 61, Short.MAX_VALUE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jtFun_morada, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtFun_nome, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jtFun_cod, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jtFun_cp, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jtFun_bi, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jtFun_telm, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel13)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jcFun_sexo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jdFun_dtReg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jdFun_dtNasc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addComponent(jtFun_email, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(15, 15, 15))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jcFun_status, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jpFun_foto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jtFun_cod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel2)
                                            .addComponent(jtFun_nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel3)
                                            .addComponent(jtFun_bi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel11)
                                            .addComponent(jtFun_telm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel8)
                                            .addComponent(jdFun_dtNasc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jcFun_sexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel13))))
                                .addGap(6, 6, 6)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel12)
                                    .addComponent(jtFun_cp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5)))
                            .addComponent(jdFun_dtReg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jtFun_morada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(jtFun_email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(jcFun_status, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jpFun_foto, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10))
        );

        javax.swing.GroupLayout jpFun_dadosLayout = new javax.swing.GroupLayout(jpFun_dados);
        jpFun_dados.setLayout(jpFun_dadosLayout);
        jpFun_dadosLayout.setHorizontalGroup(
            jpFun_dadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpFun_dadosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jpFun_dadosLayout.setVerticalGroup(
            jpFun_dadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpFun_dadosLayout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(163, Short.MAX_VALUE))
        );

        jTabFun.addTab("Dados de Funcionário", jpFun_dados);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabFun)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTabFun))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
        controllerFuncinario.preencherJTabelaFuncinario();
    }//GEN-LAST:event_formInternalFrameOpened

    private void jbEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbEditarActionPerformed
        ativarDesativaBotoes(true);
        jbNovo.setEnabled(false);
        ativarDesativarClienteCampos(true);
    }//GEN-LAST:event_jbEditarActionPerformed

    private void formInternalFrameClosing(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameClosing
        janela = 0;
    }//GEN-LAST:event_formInternalFrameClosing

    private void jlFotoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlFotoMouseClicked
        carregaFoto();
    }//GEN-LAST:event_jlFotoMouseClicked

    private void jbCli_procurarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCli_procurarActionPerformed
        carregaFoto();
    }//GEN-LAST:event_jbCli_procurarActionPerformed

    private void jbCli_limparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCli_limparActionPerformed
        jlFoto.setIcon(new ImageIcon(getClass().getResource("/imagem/fotoCliente.png")));

    }//GEN-LAST:event_jbCli_limparActionPerformed

    private void jtFun_biActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtFun_biActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtFun_biActionPerformed

    private void jtFun_telmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtFun_telmActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtFun_telmActionPerformed

    private void jtFun_moradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtFun_moradaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtFun_moradaActionPerformed

    private void jbNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbNovoActionPerformed
        jTabFun.setSelectedComponent(jpFun_dados);
        ativarDesativaBotoes(true);
        ativarDesativarClienteCampos(true);
        limparClienteCampos();
        jbNovo.setEnabled(false);
    }//GEN-LAST:event_jbNovoActionPerformed

    private void jTabFunMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTabFunMouseClicked
        if (jTabFun.getSelectedIndex() == 1) {
            ativarDesativaBotoes(true);
            ativarDesativarClienteCampos(true);
            jbNovo.setEnabled(false);
        }
    }//GEN-LAST:event_jTabFunMouseClicked

    private void jbGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbGuardarActionPerformed

        if (localFoto != null) {
            try (ByteArrayOutputStream bytesImg = new ByteArrayOutputStream()) {
                BufferedImage imagemBuffer = ImageIO.read(new File(localFoto));
                ImageIO.write((BufferedImage) imagemBuffer, "jpg", bytesImg);
                bytesImg.flush();
                bytes = bytesImg.toByteArray();
            } catch (IOException ex) {
                JOptionPane.showMessageDialog(this, "Erro" + ex.getMessage());
            }
        }
        if (jtFun_cod.getText().equals("")) {
            if (validarCampos()) {
                if (localFoto == null) {
                    JOptionPane.showMessageDialog(this, "Obrigatório carregar foto", "Carregar foto", JOptionPane.ERROR_MESSAGE);
                } else {
                    controllerFuncinario.manutencaoPessoaFuncinario("inserir", jtFun_cod.getText(), jtFun_nome.getText(), jcFun_sexo.getSelectedIndex(), jtFun_bi.getText(),
                            jtFun_email.getText(), jtFun_morada.getText(), jtFun_cp.getText(), jtFun_telm.getText(), jtFun_nome.getText(),
                            jcFun_status.getSelectedIndex(), bytes, new java.sql.Date(jdFun_dtNasc.getDate().getTime()), new java.sql.Date(jdFun_dtReg.getDate().getTime()), 1);
                    limparClienteCampos();
                    ativarDesativaBotoes(false);
                    ativarDesativarClienteCampos(false);
                    destivaAtivaBotao2(false);
                }

            }
        } else {
            if (localFoto == null) {
                controllerFuncinario.manutencaoPessoaFuncinario("alterarSemFoto", jtFun_cod.getText(), jtFun_nome.getText(), jcFun_sexo.getSelectedIndex(), jtFun_bi.getText(),
                        jtFun_email.getText(), jtFun_morada.getText(), jtFun_cp.getText(), jtFun_telm.getText(), jtFun_nome.getText(),
                        jcFun_status.getSelectedIndex(), bytes, new java.sql.Date(jdFun_dtNasc.getDate().getTime()), new java.sql.Date(jdFun_dtReg.getDate().getTime()), 1);
                limparClienteCampos();
                ativarDesativaBotoes(false);
                ativarDesativarClienteCampos(false);
                destivaAtivaBotao2(false);
            } else {
                controllerFuncinario.manutencaoPessoaFuncinario("alterar", jtFun_cod.getText(), jtFun_nome.getText(), jcFun_sexo.getSelectedIndex(), jtFun_bi.getText(),
                        jtFun_email.getText(), jtFun_morada.getText(), jtFun_cp.getText(), jtFun_telm.getText(), jtFun_nome.getText(),
                        jcFun_status.getSelectedIndex(), bytes, new java.sql.Date(jdFun_dtNasc.getDate().getTime()), new java.sql.Date(jdFun_dtReg.getDate().getTime()), 1);
                limparClienteCampos();
                ativarDesativaBotoes(false);
                ativarDesativarClienteCampos(false);
                destivaAtivaBotao2(false);
            }
        }

    }//GEN-LAST:event_jbGuardarActionPerformed

    private void jbCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCancelarActionPerformed
        limparClienteCampos();
        jbGuardar.setEnabled(false);
        jbCancelar.setEnabled(false);
        ativarDesativarClienteCampos(false);
        jbNovo.setEnabled(true);
    }//GEN-LAST:event_jbCancelarActionPerformed

    private void jtFun_codActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtFun_codActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtFun_codActionPerformed

    private void jtFuncionarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtFuncionarioMouseClicked
        if (evt.getClickCount() == 2) {
            try {
                limparClienteCampos();
                jTabFun.setSelectedIndex(1);
                ativarDesativaBotoes(false);
                ativarDesativarClienteCampos(false);
                controllerFuncinario.manutencaoPesquisa();

            } catch (IOException ex) {
                Logger.getLogger(VFuncionario.class
                        .getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jtFuncionarioMouseClicked

    private void jbApagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbApagarActionPerformed
        controllerFuncinario.manutencaoPessoaFuncinario("excluir", jtFun_cod.getText(), jtFun_nome.getText(), jcFun_sexo.getSelectedIndex(), jtFun_bi.getText(),
                jtFun_email.getText(), jtFun_morada.getText(), jtFun_cp.getText(), jtFun_telm.getText(), jtFun_nome.getText(),
                jcFun_status.getSelectedIndex(), bytes, new java.sql.Date(jdFun_dtNasc.getDate().getTime()), new java.sql.Date(jdFun_dtReg.getDate().getTime()), 1);
        limparClienteCampos();
        ativarDesativaBotoes(false);
        ativarDesativarClienteCampos(false);
        destivaAtivaBotao2(false);
    }//GEN-LAST:event_jbApagarActionPerformed

    private void jbFun_pesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbFun_pesquisarActionPerformed
          controllerFuncinario.pesquisaFuncionario("Nome",jtFun_pesq.getText());
    }//GEN-LAST:event_jbFun_pesquisarActionPerformed

    private void jbImprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbImprimirActionPerformed
        Conexao con = new Conexao();
        String nomeCliente = "Imprimir a lista de todos os Funcionário do ginásio ";
        int opcaoEscolhida = JOptionPane.showConfirmDialog(null, nomeCliente, "Confirmacão Impressão?", JOptionPane.YES_OPTION);
        if (opcaoEscolhida == JOptionPane.YES_OPTION) {
            InputStream caminho = getClass().getResourceAsStream("/relatorios/RFuncionarios.jrxml");
            con.EjecutarReporteStream(caminho);
        }
    }//GEN-LAST:event_jbImprimirActionPerformed

    private void jtFun_pesqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtFun_pesqActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtFun_pesqActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    public static javax.swing.JTabbedPane jTabFun;
    private javax.swing.JButton jbApagar;
    private javax.swing.JButton jbCancelar;
    private javax.swing.JButton jbCli_limpar;
    private javax.swing.JButton jbCli_procurar;
    private javax.swing.JButton jbEditar;
    private javax.swing.JButton jbFun_pesquisar;
    private javax.swing.JButton jbGuardar;
    private javax.swing.JButton jbImprimir;
    private javax.swing.JButton jbNovo;
    public static javax.swing.JComboBox jcFun_sexo;
    public static javax.swing.JComboBox jcFun_status;
    public static com.toedter.calendar.JDateChooser jdFun_dtNasc;
    public static com.toedter.calendar.JDateChooser jdFun_dtReg;
    public static javax.swing.JLabel jlFoto;
    private javax.swing.JPanel jpFun_dados;
    private javax.swing.JPanel jpFun_foto;
    private javax.swing.JPanel jpFun_listar;
    public static javax.swing.JTextField jtFun_bi;
    public static javax.swing.JTextField jtFun_cod;
    public static javax.swing.JTextField jtFun_cp;
    public static javax.swing.JTextField jtFun_email;
    public static javax.swing.JTextField jtFun_morada;
    public static javax.swing.JTextField jtFun_nome;
    private javax.swing.JTextField jtFun_pesq;
    public static javax.swing.JTextField jtFun_telm;
    public static javax.swing.JTable jtFuncionario;
    // End of variables declaration//GEN-END:variables

    public void setPosicao() {
        Dimension d = this.getDesktopPane().getSize();
        this.setLocation((d.width - this.getSize().width) / 2, (d.height - this.getSize().height) / 2);
    }

    public void limparClienteCampos() {
        jtFun_cod.setText("");
        jtFun_bi.setText("");
        jtFun_cp.setText("");
        jtFun_nome.setText("");
        jtFun_morada.setText("");
        jtFun_telm.setText("");
        jtFun_email.setText("");
        //jtFun_login.setText("");
        jdFun_dtNasc.setDate(null);
        jcFun_sexo.setSelectedIndex(0);
        jcFun_status.setSelectedIndex(0);
        jbCli_limparActionPerformed(null);

    }

    public void ativarDesativarClienteCampos(boolean habilitar) {
        jtFun_bi.setEditable(habilitar);
        jtFun_cp.setEditable(habilitar);
        jtFun_nome.setEditable(habilitar);
        jtFun_morada.setEditable(habilitar);
        jtFun_telm.setEditable(habilitar);
        jtFun_email.setEditable(habilitar);
        //jtFun_login.setEditable(habilitar);
        jcFun_sexo.setEnabled(habilitar);
        jcFun_status.setEnabled(habilitar);
        // jcFun_funcao.setEnabled(habilitar);
        jdFun_dtNasc.setEnabled(habilitar);
        //jlFoto.setEnabled(habilitar);
        jbCli_procurar.setEnabled(habilitar);
        jdFun_dtReg.setEnabled(habilitar);
    }

    public void ativarDesativaBotoes(boolean habilitar) {
        jbGuardar.setEnabled(habilitar);
        jbCancelar.setEnabled(habilitar);
        jbNovo.setEnabled(habilitar);
        jbEditar.setEnabled(!habilitar);
        jbApagar.setEnabled(!habilitar);
        jbImprimir.setEnabled(!habilitar);
    }

    private boolean validarCampos() {
        if ((!jtFun_email.getText().equals(""))) {
            String emailPattern;
            emailPattern = "\\b(^[_A-Za-z0-9-]+(\\.[_A-Za-z0-9-]+)*@([A-Za-z0-9-])+(\\.[A-Za-z0-9-]+)*((\\.[A-Za-z0-9]{2,})|(\\.[A-Za-z0-9]{2,}\\.[A-Za-z0-9]{2,}))$)\\b";
            Pattern pattern = Pattern.compile(emailPattern, Pattern.CASE_INSENSITIVE);
            Matcher matcher = pattern.matcher(jtFun_email.getText());
            boolean valid = matcher.matches();
            if (!valid) {
                JOptionPane.showMessageDialog(this, "Formato email invalido");
            }
            return false;

        }
        if (jtFun_telm.getText().equals("")) {
            //jtFun_telm.setBorder(new LineBorder(Color.red));
            jtFun_telm.requestFocus();
            return false;
        }
        if (jtFun_morada.getText().equals("")) {
            //jtFun_morada.setBorder(new LineBorder(Color.red));
            jtFun_morada.requestFocus();
            return false;
        }
        if (jtFun_nome.getText().equals("")) {
            //jtFun_nome.setBorder(new LineBorder(Color.red));
            jtFun_nome.requestFocus();
            return false;
        }
        if (jcFun_status.getSelectedIndex() == 0) {
           // jcFun_status.setBorder(new LineBorder(Color.red));
            jcFun_status.requestFocus();
            return false;
        }
        if (jcFun_sexo.getSelectedIndex() == 0) {
            jcFun_sexo.setBorder(new LineBorder(Color.red));
            jcFun_sexo.requestFocus();
            return false;
        }

        if (jdFun_dtNasc.getDate() == null) {
           // jdFun_dtNasc.setBorder(new LineBorder(Color.red));
            jdFun_dtNasc.requestFocus();
            return false;
        }

        return true;

    }

    public void carregaFoto() {

        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setDialogTitle("Importar imagem");

        fileChooser.setFileSelectionMode(JFileChooser.FILES_ONLY);
        FileNameExtensionFilter filter = new FileNameExtensionFilter(
                "JPG, GIF, PNG and BMP Images", "jpg", "gif", "png", "bmp");
        fileChooser.setFileFilter(filter);

        // int a = fileChooser.showOpenDialog(null);
        if (fileChooser.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
            File arquivo = fileChooser.getSelectedFile();//arquivo
            BufferedImage imagem = null;
            try {
                imagem = ImageIO.read(arquivo); //carrega a imagem real num buffer
            } catch (IOException ex) {
                Logger.getLogger(VFuncionario.class.getName()).log(Level.SEVERE, null, ex);
            }
            BufferedImage aux = new BufferedImage(130, 150, imagem.getType());//cria um buffer auxiliar com o tamanho desejado
            Graphics2D g = aux.createGraphics();//pega a classe graphics do aux para edicao
            AffineTransform at = AffineTransform.getScaleInstance((double) 130 / imagem.getWidth(), (double) 150 / imagem.getHeight());//cria a transformacao
            g.drawRenderedImage(imagem, at);//pinta e transforma a imagem real no auxiliar
            jlFoto.setIcon(new ImageIcon(aux));//seta no jlabel

            //LB_Foto.setIcon(new ImageIcon(fileChooser.getSelectedFile().getPath()));
            localFoto = fileChooser.getSelectedFile().getPath();
            jbCli_limpar.setEnabled(true);
        }
    }

    public void destivaAtivaBotao2(boolean habilitar) {
        jbNovo.setEnabled(!habilitar);
        jbEditar.setEnabled(habilitar);
        jbApagar.setEnabled(habilitar);

    }

}
