/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.ControllerRecibo;
import java.awt.Dimension;
import java.io.InputStream;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import table.Classe_CellEditor;
import table.Classe_CellRender;
import table.ModeloTabelaRecibo;
import static view.Login.con;

/**
 *
 * @author Carlos
 */
public class VGestRecibo extends javax.swing.JInternalFrame {

    int janela = 0;
    //VPagamentos pag = new VPagamentos();
    DefaultTableModel modelo = new DefaultTableModel();
    ModeloTabelaRecibo linhaTabela = new ModeloTabelaRecibo();
    
    ControllerRecibo controllerRecibo;

    public VGestRecibo() {
        initComponents();
        controllerRecibo = new ControllerRecibo();
        jtGestRecibo.setModel(modelo);
        modelo.addColumn("Estado");
        modelo.addColumn("Cliente");
        modelo.addColumn("Data");
        modelo.addColumn("Documento");
        modelo.addColumn("Num Documento");
        modelo.addColumn("Descrição");
        modelo.addColumn("Situação");

        jtGestRecibo.getColumnModel().getColumn(0).setCellEditor(new Classe_CellEditor());
        jtGestRecibo.getColumnModel().getColumn(0).setCellRenderer(new Classe_CellRender());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jbVisualizar = new javax.swing.JButton();
        jBApply = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtGestRecibo = new javax.swing.JTable();

        setClosable(true);
        setIconifiable(true);
        setResizable(true);
        setTitle("Gestão de Recibo/Factura");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameClosing(evt);
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jbVisualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/Eye.png"))); // NOI18N
        jbVisualizar.setToolTipText("Visualizar");
        jbVisualizar.setPreferredSize(new java.awt.Dimension(50, 33));
        jbVisualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbVisualizarActionPerformed(evt);
            }
        });

        jBApply.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/Apply.png"))); // NOI18N
        jBApply.setToolTipText("Confirmar");
        jBApply.setPreferredSize(new java.awt.Dimension(50, 33));
        jBApply.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBApplyActionPerformed(evt);
            }
        });

        jtGestRecibo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(jtGestRecibo);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 703, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jbVisualizar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jBApply, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 395, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbVisualizar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBApply, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formInternalFrameClosing(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameClosing
        janela = 0;
    }//GEN-LAST:event_formInternalFrameClosing

    private void jbVisualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbVisualizarActionPerformed
        if (jtGestRecibo.getSelectedRow() != -1) {
            String codPagamento = (String) jtGestRecibo.getValueAt(jtGestRecibo.getSelectedRow(), 4);
            String text = "Imprimir este recibo de pagamento ";
            int opcaoEscolhida = JOptionPane.showConfirmDialog(null, text, "Confirmacão Inpressao ", JOptionPane.YES_OPTION);
            if (opcaoEscolhida == JOptionPane.YES_OPTION) {
                InputStream caminho = getClass().getResourceAsStream("/relatorios/RRecibo.jrxml");
                con.EjectuarReporteFiltroString(codPagamento, "idPag", caminho);
            }
        }
    }//GEN-LAST:event_jbVisualizarActionPerformed

    private void jBApplyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBApplyActionPerformed
        if (jtGestRecibo.getSelectedRow() != -1) {
            String codPagamento = (String) jtGestRecibo.getValueAt(jtGestRecibo.getSelectedRow(), 4);
            controllerRecibo.manutencaoRecibo("alterar", "Recibo", codPagamento, "Recibo de Pagamento da mensalidade", "Emitida", true, 1, 0);
            modelo.setRowCount(0);
            linhaTabela.linha_tabela(7, 1, modelo, jtGestRecibo);
        }
    }//GEN-LAST:event_jBApplyActionPerformed

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
        linhaTabela.linha_tabela(7, 1, modelo, jtGestRecibo);
    }//GEN-LAST:event_formInternalFrameOpened


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBApply;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton jbVisualizar;
    private javax.swing.JTable jtGestRecibo;
    // End of variables declaration//GEN-END:variables

    public void setPosicao() {
        Dimension d = this.getDesktopPane().getSize();
        this.setLocation((d.width - this.getSize().width) / 2, (d.height - this.getSize().height) / 2);
    }
}
