/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.ControllerVenda;
import java.awt.Color;
import java.awt.Dimension;
import java.io.IOException;
import java.io.InputStream;
import java.sql.SQLException;
import java.text.ParseException;
import javax.swing.border.LineBorder;
import java.util.Calendar;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.text.DefaultFormatterFactory;
import javax.swing.text.MaskFormatter;
import persistence.Conexao;

/**
 *
 * @author Carlos
 */
public class VVenda extends javax.swing.JInternalFrame {

    int janela = 0;
    ControllerVenda controllerVenda;
    Calendar calendar = Calendar.getInstance();//Variable de Objeto Calendar
    int flag = 0;
    public static int idProduto;
    public static int quantidadeProduto;
    String ultimaVenda;
    int idVenda = 0;
    float total = 0;
    Double totalItem;
    String codigoCliente;

    /**
     * Creates new form Teste
     */
    public VVenda() {
        initComponents();
        jbNovo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbNovo.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jbNovo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        jbGuardar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbGuardar.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jbGuardar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        jbCancelar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbCancelar.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jbCancelar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        jbEditar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbEditar.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jbEditar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        jbApagar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbApagar.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jbApagar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        jbImprimir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbImprimir.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jbImprimir.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        Date ds = new Date();
        jdVen_data.setDate(ds);

        jtVenda.setAutoCreateRowSorter(true);
//
//        try {
//            MaskFormatter maskFormatter = new MaskFormatter("##/##/####");
//            jtProd_DataPesquisa.setFormatterFactory(new DefaultFormatterFactory(maskFormatter));
//        } catch (ParseException ex) {
//            Logger.getLogger(VVenda.class.getName()).log(Level.SEVERE, null, ex);
//        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jbNovo = new javax.swing.JButton();
        jbGuardar = new javax.swing.JButton();
        jbEditar = new javax.swing.JButton();
        jbApagar = new javax.swing.JButton();
        jbCancelar = new javax.swing.JButton();
        jbImprimir = new javax.swing.JButton();
        jTabCli = new javax.swing.JTabbedPane();
        jpVeni_listar = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jButtonPesquisar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtVenda = new javax.swing.JTable();
        jCheckBox2 = new javax.swing.JCheckBox();
        jtProd_DataPesquisa = new com.toedter.calendar.JDateChooser();
        jpVen_dados = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jtVen_nomeCliente = new javax.swing.JTextField();
        jtVen_nomeProduto = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jtCodBarra = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jtVen_Quant = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jtVen_valor = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jdVen_data = new com.toedter.calendar.JDateChooser();
        jTValorTotal = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableItensVenda = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTablePesquisa = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        jBAdd = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jTextFieldAPagar = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();

        setClosable(true);
        setIconifiable(true);
        setResizable(true);
        setTitle("Manutenção de Vendas");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameClosing(evt);
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
        });

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Opções");

        jbNovo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/Add.png"))); // NOI18N
        jbNovo.setText("Novo");
        jbNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbNovoActionPerformed(evt);
            }
        });

        jbGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/salvar.png"))); // NOI18N
        jbGuardar.setText("Guardar");
        jbGuardar.setEnabled(false);
        jbGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbGuardarActionPerformed(evt);
            }
        });

        jbEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/Modify.png"))); // NOI18N
        jbEditar.setText("Editar");
        jbEditar.setEnabled(false);
        jbEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbEditarActionPerformed(evt);
            }
        });

        jbApagar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/Remove.png"))); // NOI18N
        jbApagar.setText("Apagar");
        jbApagar.setEnabled(false);
        jbApagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbApagarActionPerformed(evt);
            }
        });

        jbCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/Close.png"))); // NOI18N
        jbCancelar.setText("Cancelar");
        jbCancelar.setEnabled(false);
        jbCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCancelarActionPerformed(evt);
            }
        });

        jbImprimir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/Print.png"))); // NOI18N
        jbImprimir.setText("Imprimir");
        jbImprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbImprimirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jbCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jbEditar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jbApagar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jbNovo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jbGuardar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jbImprimir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbNovo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbGuardar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbEditar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbApagar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbCancelar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jbImprimir)
                .addContainerGap())
        );

        jTabCli.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTabCli.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTabCliMouseClicked(evt);
            }
        });

        jLabel13.setText("Data:");

        jButtonPesquisar.setText("Pesquisar");
        jButtonPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPesquisarActionPerformed(evt);
            }
        });

        jtVenda.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Cod", "Nome", "Quantidade", "Valor", "Data"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtVenda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtVendaMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jtVenda);
        if (jtVenda.getColumnModel().getColumnCount() > 0) {
            jtVenda.getColumnModel().getColumn(0).setMinWidth(45);
            jtVenda.getColumnModel().getColumn(0).setMaxWidth(45);
            jtVenda.getColumnModel().getColumn(2).setMinWidth(80);
            jtVenda.getColumnModel().getColumn(2).setMaxWidth(80);
            jtVenda.getColumnModel().getColumn(3).setMinWidth(80);
            jtVenda.getColumnModel().getColumn(3).setMaxWidth(80);
            jtVenda.getColumnModel().getColumn(4).setMinWidth(80);
            jtVenda.getColumnModel().getColumn(4).setMaxWidth(80);
        }

        jCheckBox2.setText("Exibe todas Vendas");
        jCheckBox2.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jCheckBox2StateChanged(evt);
            }
        });

        javax.swing.GroupLayout jpVeni_listarLayout = new javax.swing.GroupLayout(jpVeni_listar);
        jpVeni_listar.setLayout(jpVeni_listarLayout);
        jpVeni_listarLayout.setHorizontalGroup(
            jpVeni_listarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpVeni_listarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpVeni_listarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 609, Short.MAX_VALUE)
                    .addGroup(jpVeni_listarLayout.createSequentialGroup()
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtProd_DataPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonPesquisar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jCheckBox2)))
                .addContainerGap())
        );
        jpVeni_listarLayout.setVerticalGroup(
            jpVeni_listarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpVeni_listarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpVeni_listarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jtProd_DataPesquisa, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpVeni_listarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jCheckBox2)
                        .addComponent(jButtonPesquisar)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 401, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabCli.addTab("Lista de Venda", jpVeni_listar);

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder("Processar Vendas"));

        jLabel4.setText("Nome Produto");

        jLabel14.setText("Nome Cliente");

        jtVen_nomeCliente.setEditable(false);
        jtVen_nomeCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtVen_nomeClienteActionPerformed(evt);
            }
        });

        jtVen_nomeProduto.setEditable(false);
        jtVen_nomeProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtVen_nomeProdutoActionPerformed(evt);
            }
        });

        jLabel2.setText("Cod. Barra");

        jtCodBarra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtCodBarraActionPerformed(evt);
            }
        });

        jLabel16.setText("Quantidade");

        jtVen_Quant.setEditable(false);
        jtVen_Quant.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtVen_QuantFocusGained(evt);
            }
        });
        jtVen_Quant.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtVen_QuantKeyTyped(evt);
            }
        });

        jLabel15.setText("Valor Por Item");

        jtVen_valor.setEditable(false);

        jLabel8.setText("Data Venda");

        jdVen_data.setEnabled(false);

        jLabel3.setText("Valor Total Item");

        jTableItensVenda.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTableItensVenda);

        jLabel5.setText("Tabela Pesquisa");

        jTablePesquisa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTablePesquisa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTablePesquisaMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jTablePesquisa);

        jLabel6.setText("Itens da Venda");

        jBAdd.setText("ADD");
        jBAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAddActionPerformed(evt);
            }
        });

        jLabel7.setText("Total a Pagar:");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jtCodBarra, javax.swing.GroupLayout.DEFAULT_SIZE, 225, Short.MAX_VALUE)
                                .addComponent(jtVen_nomeProduto))
                            .addComponent(jLabel8)
                            .addComponent(jdVen_data, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtVen_nomeCliente)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jtVen_Quant, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jtVen_valor)))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(jLabel14)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTValorTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3))
                                .addGap(18, 18, 18)
                                .addComponent(jBAdd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 577, Short.MAX_VALUE)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldAPagar, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jSeparator2))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jtCodBarra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtVen_nomeCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel16)
                        .addComponent(jLabel15)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtVen_nomeProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtVen_Quant, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtVen_valor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTValorTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBAdd)))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jdVen_data, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jTextFieldAPagar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jpVen_dadosLayout = new javax.swing.GroupLayout(jpVen_dados);
        jpVen_dados.setLayout(jpVen_dadosLayout);
        jpVen_dadosLayout.setHorizontalGroup(
            jpVen_dadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpVen_dadosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jpVen_dadosLayout.setVerticalGroup(
            jpVen_dadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpVen_dadosLayout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 5, Short.MAX_VALUE))
        );

        jTabCli.addTab("Venda", jpVen_dados);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabCli)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTabCli)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
        controllerVenda = new ControllerVenda();
        controllerVenda.preencherJTabelaVenda();
    }//GEN-LAST:event_formInternalFrameOpened

    private void jbEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbEditarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbEditarActionPerformed

    private void formInternalFrameClosing(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameClosing
        janela = 0;
    }//GEN-LAST:event_formInternalFrameClosing

    private void jbNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbNovoActionPerformed
        if (idVenda == 0) {
            controllerVenda.manutencaoVendaIncial(Principal.id, new java.sql.Date(jdVen_data.getDate().getTime()));
        }
        jTabCli.setSelectedComponent(jpVen_dados);
        ativarDesativaBotoes(false);
        ativarDesativarClienteCampos(true);
        limparClienteCampos();
        jbGuardar.setEnabled(false);
    }//GEN-LAST:event_jbNovoActionPerformed

    private void jbGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbGuardarActionPerformed
        if (validarCampos()) {
            if (jtVen_nomeCliente.getText().equals("")) {
                JOptionPane.showMessageDialog(this, "Error: Escolhe o cliente");
            } else {
                if (controllerVenda.manutencaoVendaFinal("inserirVenda", new java.sql.Date(jdVen_data.getDate().getTime()), Integer.parseInt(codigoCliente), Float.parseFloat(jTextFieldAPagar.getText()), Principal.id, idVenda)) {
                    limparClienteCampos();
                    emitirReciboVenda();
                    idVenda = 0;
                }
            }
        }


    }//GEN-LAST:event_jbGuardarActionPerformed

    private void jbCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCancelarActionPerformed
        limparClienteCampos();
        ativarDesativaBotoes(true);
        ativarDesativarClienteCampos(false);
        if (idVenda != 0) {
            try {
                controllerVenda.cancelaVenda();
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, "Error: ao cancelar venda " + ex);
            }
        }
    }//GEN-LAST:event_jbCancelarActionPerformed

    private void jTabCliMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTabCliMouseClicked
        if (jTabCli.getSelectedIndex() == 1) {
            ativarDesativaBotoes(true);
            ativarDesativarClienteCampos(true);
            jbNovo.setEnabled(false);
        }
    }//GEN-LAST:event_jTabCliMouseClicked

    private void jtCodBarraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtCodBarraActionPerformed
//        try {
//            controllerVenda.manutencaoPesquisa(jtCodBarra.getText());
//        } catch (IOException ex) {
//            Logger.getLogger(VVenda.class.getName()).log(Level.SEVERE, null, ex);
//        }
    }//GEN-LAST:event_jtCodBarraActionPerformed

    private void jtVen_nomeClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtVen_nomeClienteActionPerformed
//        try {
//            controllerVenda.manutencaoPesquisaCodigo(jtVen_cod.getText());
//        } catch (IOException ex) {
//            Logger.getLogger(VVenda.class.getName()).log(Level.SEVERE, null, ex);
//        }
        flag = 1;
        controllerVenda.preencherJTabelaPesquisaCliente(jtVen_nomeCliente.getText());
    }//GEN-LAST:event_jtVen_nomeClienteActionPerformed

    private void jtVen_nomeProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtVen_nomeProdutoActionPerformed
        try {

            ultimaVenda = controllerVenda.getUltimoRegistro().getString("ven_id");
            idVenda = Integer.parseInt(ultimaVenda);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Error ao selecionar ultimo registro :" + ex);
        }

        flag = 2;
        controllerVenda.preencherJTabelaPesquisaProduto(jtVen_nomeProduto.getText());
    }//GEN-LAST:event_jtVen_nomeProdutoActionPerformed

    private void jTablePesquisaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTablePesquisaMouseClicked
        if (flag == 1) {
            String nome_cliente = "" + jTablePesquisa.getValueAt(jTablePesquisa.getSelectedRow(), 1);
            jtVen_nomeCliente.setText(nome_cliente);
            codigoCliente = "" + jTablePesquisa.getValueAt(jTablePesquisa.getSelectedRow(), 0);
        } else {
            String nome_produto = "" + jTablePesquisa.getValueAt(jTablePesquisa.getSelectedRow(), 1);
            try {
                //            jtVen_nomeProduto.setText(nome_produto);
                controllerVenda.manutencaoPesquisaNome(nome_produto);
                jtVen_Quant.setText("1");
                totalItem = Double.parseDouble(jtVen_valor.getText()) * Integer.parseInt(jtVen_Quant.getText());
                jTValorTotal.setText(String.valueOf(totalItem));
                flag = 3;
            } catch (IOException ex) {
                Logger.getLogger(VVenda.class.getName()).log(Level.SEVERE, null, ex);
            }
        }


    }//GEN-LAST:event_jTablePesquisaMouseClicked

    private void jtVen_QuantFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtVen_QuantFocusGained
//        totalItem = Float.parseFloat(jtVen_valor.getText()) * Integer.parseInt(jtVen_Quant.getText());
//        jTValorTotal.setText(String.valueOf(totalItem));

    }//GEN-LAST:event_jtVen_QuantFocusGained

    private void jBAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAddActionPerformed
        if (jtVen_nomeProduto.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Error: Escolhe um produto!");
        } else {
            if (controllerVenda.verificaQuantidadeProduto(jtVen_nomeProduto.getText())) {
                if (controllerVenda.manutencaoVenda("inserir", jtVen_Quant.getText(), idVenda, idProduto, Float.parseFloat(jtVen_valor.getText()))) {
                    controllerVenda.upadateQuantidadeProduto(quantidadeProduto, jtVen_nomeProduto.getText());
                    controllerVenda.preencherJTabelaItemVenda(idVenda);
                }
                // total = total + (Float.parseFloat(jtVen_valor.getText()) * Integer.parseInt(jtVen_Quant.getText()));
                // jTextFieldAPagar.setText(String.valueOf(total));
                jbGuardar.setEnabled(true);
            }
        }

    }//GEN-LAST:event_jBAddActionPerformed
    public void emitirReciboVenda() {
        Conexao con = new Conexao();
        String nomeCliente = "Imprimir este recibo de pagamento venda ";
        int opcaoEscolhida = JOptionPane.showConfirmDialog(null, nomeCliente, "Confirmacão Inpressao ", JOptionPane.YES_OPTION);
        if (opcaoEscolhida == JOptionPane.YES_OPTION) {
            InputStream caminho = getClass().getResourceAsStream("/relatorios/RReciboVenda.jrxml");
            con.EjectuarReporteFiltroString(String.valueOf(idVenda), "idPag", caminho);
        }
    }
    private void jtVen_QuantKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtVen_QuantKeyTyped
        char c = evt.getKeyChar();
        if (!jtVen_Quant.getText().equals("")) {
            if (c < '0' || c > '9') {
                evt.consume();
                if (flag == 3) {
                    totalItem = Double.parseDouble(jtVen_valor.getText()) * Integer.parseInt(jtVen_Quant.getText());
                    jTValorTotal.setText(String.valueOf(totalItem));
                }
            }
        }
    }//GEN-LAST:event_jtVen_QuantKeyTyped

    private void jbApagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbApagarActionPerformed

    }//GEN-LAST:event_jbApagarActionPerformed

    private void jButtonPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPesquisarActionPerformed
        if (new java.sql.Date(jtProd_DataPesquisa.getDate().getTime()).toString().equals("")) {

        } else {
            controllerVenda.preencherJTabelaVenda(new java.sql.Date(jtProd_DataPesquisa.getDate().getTime()));
        }
    }//GEN-LAST:event_jButtonPesquisarActionPerformed

    private void jtVendaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtVendaMouseClicked

    }//GEN-LAST:event_jtVendaMouseClicked

    private void jCheckBox2StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jCheckBox2StateChanged
        if (jCheckBox2.isSelected()) {
            controllerVenda.preencherJTabelaVenda();
        }
    }//GEN-LAST:event_jCheckBox2StateChanged

    private void jbImprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbImprimirActionPerformed
        Conexao con = new Conexao();

        String nomeCliente = "Imprimir a lista de todas vendas do ginásio ";
        int opcaoEscolhida = JOptionPane.showConfirmDialog(null, nomeCliente, "Confirmacão Inpressao ", JOptionPane.YES_OPTION);

        if (opcaoEscolhida == JOptionPane.YES_OPTION) {
            InputStream caminho = getClass().getResourceAsStream("/relatorios/RVenda.jrxml");
            con.EjecutarReporte(caminho);

        }
    }//GEN-LAST:event_jbImprimirActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBAdd;
    private javax.swing.JButton jButtonPesquisar;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField jTValorTotal;
    private javax.swing.JTabbedPane jTabCli;
    public static javax.swing.JTable jTableItensVenda;
    public static javax.swing.JTable jTablePesquisa;
    public static javax.swing.JTextField jTextFieldAPagar;
    private javax.swing.JButton jbApagar;
    private javax.swing.JButton jbCancelar;
    private javax.swing.JButton jbEditar;
    private javax.swing.JButton jbGuardar;
    private javax.swing.JButton jbImprimir;
    private javax.swing.JButton jbNovo;
    public static com.toedter.calendar.JDateChooser jdVen_data;
    private javax.swing.JPanel jpVen_dados;
    private javax.swing.JPanel jpVeni_listar;
    public static javax.swing.JTextField jtCodBarra;
    private com.toedter.calendar.JDateChooser jtProd_DataPesquisa;
    public static javax.swing.JTextField jtVen_Quant;
    public static javax.swing.JTextField jtVen_nomeCliente;
    public static javax.swing.JTextField jtVen_nomeProduto;
    public static javax.swing.JTextField jtVen_valor;
    public static javax.swing.JTable jtVenda;
    // End of variables declaration//GEN-END:variables
    public void setPosicao() {
        Dimension d = this.getDesktopPane().getSize();
        this.setLocation((d.width - this.getSize().width) / 2, (d.height - this.getSize().height) / 2);
    }

    public void limparClienteCampos() {
        jtVen_nomeCliente.setText("");
        jtVen_nomeProduto.setText("");
        jtVen_valor.setText("");
        jtVen_Quant.setText("");
        jTextFieldAPagar.setText("");
        jTValorTotal.setText("");
    }

    public void ativarDesativarClienteCampos(boolean habilitar) {
        jtVen_nomeProduto.setEditable(habilitar);
        jtVen_valor.setEditable(habilitar);
        jtVen_Quant.setEditable(habilitar);
        jtCodBarra.setEditable(habilitar);
        jtVen_nomeCliente.setEditable(habilitar);
        jTValorTotal.setEditable(habilitar);
    }

    public void ativarDesativaBotoes(boolean habilitar) {
        jbGuardar.setEnabled(!habilitar);
        jbCancelar.setEnabled(!habilitar);
        jbNovo.setEnabled(habilitar);
        jBAdd.setEnabled(!habilitar);
        // jbApagar.setEnabled(!habilitar);
        jbImprimir.setEnabled(habilitar);
    }

    private boolean validarCampos() {

        if (jtVen_nomeProduto.getText().equals("")) {
            jtVen_nomeProduto.setBorder(new LineBorder(Color.red));
            jtVen_nomeProduto.requestFocus();
            return false;
        }
        if (jtVen_valor.getText().equals("")) {
            jtVen_valor.setBorder(new LineBorder(Color.red));
            jtVen_valor.requestFocus();
            return false;
        }
        if (jtVen_Quant.getText().equals("")) {
            jtVen_Quant.setBorder(new LineBorder(Color.red));
            jtVen_Quant.requestFocus();
            return false;
        }
        return true;

    }
}
